export const Product_Dummy_Data = [
  {
    id: 1,
    Product_Name: "Running Shoes",
    Price: "₹299",
    Companie: "Nike",
    delivery_charge: "₹50",
    Quality: "★★★★★",
    img_src: "https://m.media-amazon.com/images/I/615GVWgMURL._SY625_.jpg",
  },
  {
    id: 2,
    Product_Name: "Casual Sneakers",
    Price: "₹299",
    Companie: "Adidas",
    delivery_charge: "₹50",
    Quality: "★★★★☆",
    img_src: "https://m.media-amazon.com/images/I/615GxgLBp7L._SY695_.jpg",
  },

  {
    id: 3,
    Product_Name: "Formal Leather Shoes",
    Price: "₹299",
    Companie: "Bata",
    delivery_charge: "₹50",
    Quality: "★★★★☆",
    img_src:
      "https://images-eu.ssl-images-amazon.com/images/I/81y60Nc9jeL._AC_UL232_SR232,232_.jpg",
  },
  {
    id: 4,
    Product_Name: "	Sports Shoes",
    Price: "₹299",
    Companie: "Puma",
    delivery_charge: "₹50",
    Quality: "★★★★★",
    img_src: "https://m.media-amazon.com/images/I/71zMyHOWl+L._SY625_.jpg",
  },
  {
    id: 5,
    Product_Name: "Loafers",
    Price: "₹299",
    Companie: "Red Tape",
    delivery_charge: "₹50",
    Quality: "★★★★☆",
    img_src: "https://m.media-amazon.com/images/I/71N6mH2rA4L._SY625_.jpg",
  },
  {
    id: 6,
    Product_Name: "High Ankle Boots",
    Price: "₹299",
    Companie: "Woodland",
    delivery_charge: "₹50",
    Quality: "★★★★★",
    img_src: "https://m.media-amazon.com/images/I/415J19DtPTL._SY695_.jpg",
  },
  {
    id: 7,
    Product_Name: "Canvas Shoes",
    Price: "₹299",
    Companie: "Converse",
    delivery_charge: "₹50",
    Quality: "★★★★☆",
    img_src: "https://m.media-amazon.com/images/I/61g0hpUI9YL._SY625_.jpg",
  },
  {
    id: 8,
    Product_Name: "Flip Flops",
    Price: "₹599",
    Companie: "Sparx",
    delivery_charge: "₹10",
    Quality: "★★★☆☆",
    img_src: "https://m.media-amazon.com/images/I/718yGCyz7KL._SY625_.jpg",
  },

  {
    id: 9,
    Product_Name: "Sandals",
    Price: "₹899",
    Companie: "Action",
    delivery_charge: "₹15",
    Quality: "★★★★☆",
    img_src: "	https://m.media-amazon.com/images/I/71aBewfWBwL._SY625_.jpg",
  },
  {
    id: 10,
    Product_Name: "Trekking Shoes",
    Price: "₹4,499",
    Companie: "Decathlon",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src: "https://m.media-amazon.com/images/I/41NouCvrMML._SY695_.jpg",
  },
  {
    id: 11,
    Product_Name: "Waterproof Shoes",
    Price: "₹40,499",
    Companie: "Timberland",
    delivery_charge: "₹10",
    Quality: "★★★★★",
    img_src: "https://m.media-amazon.com/images/I/71Y8t1ou+ML._SY625_.jpg",
  },
  {
    id: 12,
    Product_Name: "Gym Training Shoes",
    Price: "₹2,799",
    Companie: "Reebok",
    delivery_charge: "₹50",
    Quality: "★★★★★",
    img_src: "https://m.media-amazon.com/images/I/7112B3NZr+L._SY675_.jpg",
  },
  {
    id: 13,
    Product_Name: "Golf Shoes",
    Price: "₹4,499",
    Companie: "Nike Golf",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src: "https://m.media-amazon.com/images/I/719wPs8uZGL._SY625_.jpg",
  },
  {
    id: 14,
    Product_Name: "Cricket Shoes",
    Price: "₹4,499",
    Companie: "Adidas",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src: "https://m.media-amazon.com/images/I/419vnRwtJnL._SY695_.jpg",
  },
  {
    id:15,
    Product_Name: "Hiking Boots",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src: "https://m.media-amazon.com/images/I/71cflgAolqL._SY625_.jpg",
  },
];

export const Dummy_Girl_Shoes_Data = [
  {
    Product_Name: "Hiking Boots",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",

    img_src:
      "https://images.meesho.com/images/products/439188836/fyj0d_400.webp",
  },
  {
    Product_Name: "Cricket Shoes",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src:
      "https://images.meesho.com/images/products/476412269/mgd3n_512.webp",
  },
  {
    Product_Name: "Golf Shoes",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src:
      "https://5.imimg.com/data5/SELLER/Default/2023/12/365430631/LB/YJ/FA/6215968/casual-women-shoes.jpg",
  },
  {
    Product_Name: "Gym Training Shoes",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src: "https://m.media-amazon.com/images/I/51KPSGeSasL._SY625_.jpg",
  },
  {
    Product_Name: "Hiking Boots",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src: "	https://m.media-amazon.com/images/I/61ajPNzlDLL._SY625_.jpg",
  },
  {
    Product_Name: "Comfortable-ons",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src:
      "https://images.meesho.com/images/products/149032348/wtspi_400.webp",
  },
  {
    Product_Name: "Trendy Canvas",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src:
      "	https://5.imimg.com/data5/ANDROID/Default/2022/2/QB/CV/LU/73718625/product-jpeg-1000x1000.jpg",
  },
  {
    Product_Name: "Chunky  Sneakers",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src:
      "	https://images.meesho.com/images/products/359142259/rp9qd_400.webp",
  },
  {
    Product_Name: "Hiking Boots",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src:
      "https://images.meesho.com/images/products/81736682/bwk2w_400.webp",
  },
  {
    Product_Name: "Comfortable-ons",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src:
      "	https://images.meesho.com/images/products/81736189/8hapq_400.webp",
  },
  {
    Product_Name: "Flip Flops",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src: "https://m.media-amazon.com/images/I/61BOt894PEL._SY625_.jpg",
  },
  {
    Product_Name: "Casual Sneakers",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src:
      "	https://images.meesho.com/images/products/230142320/bkhlr_400.webp",
  },
  {
    Product_Name: "Chunky Sneakers",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src:
      "https://images.meesho.com/images/products/251067547/5nrd3_400.webp",
  },
  {
    Product_Name: "Hiking Boots",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src:
      "	https://images.meesho.com/images/products/400642463/ehpki_400.webp",
  },
  {
    Product_Name: "Pink Mesh",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src:
      "https://images.meesho.com/images/products/359912215/oavji_512.webp",
  },
  {
    Product_Name: "Formal Leather ",
    Price: "₹4,499",
    Companie: "Columbia",
    delivery_charge: "₹80",
    Quality: "★★★★★",
    img_src: "https://m.media-amazon.com/images/I/61BOt894PEL._SY625_.jpg",
  },
];
